### ISSUE TITLE
Missing CMakeLists.txt in MAMchem_GridComp/optics

### ISSUE THREAD

**Issue by adarmenov** [GEOS-ESM/GEOSchem_GridComp#36]
MAMchem_GridComp/optics/ does not contain a CMakeLists.txt, and cannot be compiled/used 'out of the box'. 

The code in this directory is self-contained and does not have outside dependencies, besides commonly used python modules.

**Comment by tclune** [comment]
Sorry @adarmenov - I'm still catching up from travel over a week ago and only today starting to delve into GitHub issues that have been assigned to me.     I do think Matt mentioned this issue to me last week, but it may not be the same one.

I'll take a look, but it might still be a few days before I can provide a solution.

**Comment by mathomp4** [comment]
I'm getting close on this. I've had to do some *ugly* hacks to `UseF2Py.cmake` but I think I'm close.

**Comment by mathomp4** [comment]
@adarmenov Okay, I think I now have a first shot at this on Github. You need to checkout the branch:
```
feature/mathomp4/#36-add-optics-cmake
```
in here and in ESMA_cmake because I had to make a big change to the `Use_F2Py.cmake` file. I know the `optics_.so` is made and installed in `${CMAKE_INSTALL_PREFIX}/lib/Python/optics` and I can run:
```
python -c 'import optics_'
```
and it doesn't complain.
