### ISSUE TITLE
passing info to the setup script

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/GEOSchem_GridComp#9]
In the old implementation, the stratchem_setup  script would scan the
StratChem GNUmakefile, to see if the user had added a compile flag
to produce a reduced chemical mechanism.  If so, it would automatically
edit the Chem_Registry to remove some of the species.
In the new CMake approach, I can easily add the compile flag back in (it had been deleted),
but stratchem_setup  doesn't have a convenient way to refer back to the CMakeLists.txt
under StratChem_GridComp, does it?  Is there a recommended way for
stratchem_setup in install/bin  to get info about compile flags used for StratChem?

**Comment by tclune** [comment]
@mmanyin  It may be more useful to think of having both the compile flags _and_ the registry both derived from some separate option rather than trying to interpret the compile flags.   Possibly I've misunderstood, or maybe I'm just splitting hairs.

I may try to swing by to understand things a bit more.   I think it will be easy to do what is needed.

**Comment by tclune** [comment]
@mmanyin looks like you had left by the time I got to your office, so I looked a bit at this on my own.       I think the better solution is to exploit the fact that stratchem_setup is actually a template.   When it is instantiated into the install directory, CMake can "fill" the value for R.

I can make an attempt at this in the morning before I leave on travel, but if I'm unsuccessful, I'm certain @mathomp4 can help.  (He's done very similar things in other setup scripts.)

The first step will be to make DREDUCED a cached option for CMake.    One would then set it during the build my appending ```-DREDUCED=ON``` to the initial cmake command.  (Matt may need to add this to the parallel_build.csh if blackbox users may need it.)

Longer term, would it make more sense to have the runtime code reinterpret the registry rather than editing it during the setup?   Just curious.

**Comment by mathomp4** [comment]
Okay. I took a look at the `stratchem_setup` and I think it should be fairly simple to embed a cached variable in it using `configure_file`. I also stared at `gmichem_setup` and it doesn't seem to have any "look back at `src`" issue, right?

**Comment by tclune** [comment]
@mathomp4     We might want to also change the name for the flag so that it identifies the component in some way.   Just fearing a growing list of "global" CMake variables.

**Comment by mathomp4** [comment]
@tclune True. Something like `-DSTRATCHEM_REDUCED_MECHANISM=ON` is probably a better name. Or, I suppose we don't need all caps: `-DStratChem_Reduced_Mechanism=ON` is just as usable.

**Comment by tclune** [comment]
I guess I modestly prefer all caps if it is not too late.      Wish that CMake had not chosen "Fortran" instead of "FORTRAN" for their defs - otherwise it would be a common convention to use all caps.

**Comment by mathomp4** [comment]
Not too late at all, I'm currently in "working on latest FMS" mode. But I'll tackle this soon. It's probably best if @mmanyin sees this for me to come to him or he to me so I can be sure about what he wants and how things work.

**Comment by mmanyin** [comment]
Catching up here…   It’s fine to have the compilation and the setup script affected by a single CMake flag.  I agree the name of the flag should include StratChem in it,
so your recent proposals are fine.  The compile option should still be -DREDUCED, in the StratChem subdirectory, OK?
And Matt is right,  GMI does not pull this trick, only StratChem does.
I don’t want to re-engineer this approach if I don’t have to.
It will need to work for black box users, but it is not the primary mode of running.

My working version of stratchem_setup is here:   /gpfsm/dnb02/projects/p128/mmanyin/GIT/GEOSgcm/install/bin/stratchem_setup

thanks,
Mike

**Comment by tclune** [comment]
@mmanyin  A side comment.   I strongly recommend following the links and responding to tickets from within the browser on the GitHub site instead of directly replying by mail.   There is often useful metadata  there and it avoids accumulation of previous messages.

Nothing ironclad here, just trying to target our main gatekeepers in the hopes that others can then pick up on their good habits.

**Comment by mmanyin** [comment]
OK Tom,  will do!
